### ISSUE TITLE
Error when starting ES search node with a lot of initial data.

### ISSUE THREAD

**Issue by masda70** [thymeflow/thymeflow-back#3]
```
11:56:57.260 [thymeflow-akka.actor.default-dispatcher-9] INFO  c.t.t.s.e.FullTextSearchServer$ - [elastic-search] Started search node.
11:57:29.655 [thymeflow-akka.actor.default-dispatcher-9] ERROR com.thymeflow.actors.package$ - org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping [literal]) within 30s
    at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:278)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by masda70** [comment]
Fixed by https://github.com/thymeflow/thymeflow-back/commit/92cf9e9c3cbec11c4e7c0dcd51cc8464c776f3ad
